AWSTemplateFormatVersion: '2010-09-09'
Description: 'Demonstration of infrastructure as code by building a code pipeline from source'

# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
Parameters:

  # https://aws.amazon.com/blogs/mt/using-aws-systems-manager-parameter-store-secure-string-parameters-in-aws-cloudformation-templates/
  GitHubOAuthToken:
    Type: AWS::SSM::Parameter::Value<String>
    Default: CodePipelineDemo

Resources:

  # https://docs.aws.amazon.com/codepipeline/latest/userguide/pipelines-webhooks-create-cfn.html
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codepipeline-webhook.html
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-webhook-webhookauthconfiguration.html
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-webhook-webhookfilterrule.html

  Webhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Name: DefaultWebhook
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: !Ref GitHubOAuthToken
      Filters:
        - JsonPath: '$.ref'
          MatchEquals: !Sub refs/heads/master
      TargetAction: UpdateFromSource
      TargetPipeline: !Ref CodePipeline
      TargetPipelineVersion: !GetAtt CodePipeline.Version
      RegisterWithThirdParty: true

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-policy.html
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - 'codepipeline.amazonaws.com'
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "demonstration"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "*" # Don't do this; it allows the role to perform all actions on it's resources!
                Resource: "*" # Don't do this; it allows the role to perform it's actions on all resources!

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html
  CodePipelineArtifactStore:
    Type: AWS::S3::Bucket

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
  DefaultCodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - 'codebuild.amazonaws.com'
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "demonstration"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "*" # NO!
                Resource: "*" # NO!

  # https://docs.aws.amazon.com/codebuild/latest/userguide/concepts.html#concepts-how-it-works
  # https://docs.aws.amazon.com/codebuild/latest/userguide/getting-started.html
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html
  DefaultCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:2.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
        -
          Name: ARTIFACT_STORE
          Value: !Ref CodePipelineArtifactStore
      ServiceRole: !GetAtt DefaultCodeBuildRole.Arn
      Source:
        BuildSpec: source/buildspec.yml
        Type: CODEPIPELINE

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codepipeline-pipeline.html
  # https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-pipeline-structure.html
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-pipeline-artifactstore.html
  # https://docs.aws.amazon.com/codebuild/latest/userguide/how-to-create-pipeline.html
  # https://docs.aws.amazon.com/codepipeline/latest/userguide/pipelines-create.html
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: DefaultPipeline
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Location: !Ref CodePipelineArtifactStore
        Type: S3
      Stages:

      - Name: Source
        Actions:
        -
          Name: UpdateFromSource
          ActionTypeId:
            Category: Source
            Owner: ThirdParty
            Provider: GitHub
            Version: 1
          OutputArtifacts:
            - Name: SourceOutput
          Configuration:
            Owner: buglass
            Repo: aws-introduction
            Branch: master
            OAuthToken: !Ref GitHubOAuthToken
            PollForSourceChanges: false
          RunOrder: 1

      - Name: Build
        Actions:
        -
          Name: BuildPackage
          ActionTypeId:
            Category: Build
            Owner: AWS
            Provider: CodeBuild
            Version: 1
          InputArtifacts:
            - Name: SourceOutput
          Configuration:
            ProjectName: !Ref DefaultCodeBuild
          RunOrder: 1