# https://docs.aws.amazon.com/codebuild/latest/userguide/concepts.html#concepts-how-it-works
# https://docs.aws.amazon.com/codebuild/latest/userguide/getting-started.html
# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
# https://github.com/aws-samples/lambda-go-samples/blob/master/buildspec.yml

version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.12

  build:
    commands:
      # build go application
      - go build -o main

      # Package application with AWS SAM
      # https://docs.aws.amazon.com/cli/latest/reference/cloudformation/package.html
      - aws cloudformation package --template-file template.yml --s3-bucket ${ARTIFACT_STORE} --output-template-file packaged-source.yml


artifacts:
  files:
    packaged-source.yml